### ISSUE TITLE
Broken link in `components/ApiWarning.mdx` when deep linked

### ISSUE THREAD

**Issue by Shrinks99** [hyphacoop/docs.distributed.press#3]
The link to "self host" on https://docs.distributed.press/deployment is broken as the ApiWarning call-out [linked on that page](https://github.com/hyphacoop/docs.distributed.press/blob/main/pages/deployment/index.mdx) is [using relative links](https://github.com/hyphacoop/docs.distributed.press/blob/c82e74d9d6a88c70c1e87013a07aa4845c74f57b/components/ApiWarning.mdx?plain=1#L4) which don't correspond to how it may be used when a section has been deep linked.  This issue is probably larger in scope than just this link as it would likely apply to any link on the site that has been deep linked to as your docs use actual paths (docs.distributed.press/page/deeplink) instead of IDs (docs.distributed.press/page#deeplink)

**Comment by Shrinks99** [comment]
Sorry, wasn't about deep links 😅 

Seems to just be a pathing issue between https://docs.distributed.press/deployment and https://docs.distributed.press/deployment/github-actions which have different paths but the same component is used on both of them.

**Comment by jackyzha0** [comment]
All good! Thanks for reporting :) Should be fixed now
